kind: pipeline
name: default

steps:

- name: build
  image: pfeifenjoy/logging.h
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..

- name: test
  image: pfeifenjoy/logging.h
  commands:
  - cd build
  - ctest --verbose .
  - cd ..

- name: memcheck
  image: pfeifenjoy/logging.h
  commands:
  - valgrind --leak-check=yes --error-exitcode=1 --suppressions=./.valgrind-suppressions ./build/example

- name: package
  image: pfeifenjoy/logging.h
  commands:
  - cd build
  - cpack .
  - cd ..

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
        from_secret: gitea_token
    base_url: https://gitea.metthub.de
    files: build/logging.h-*
  checksum:
    - md5
    - sha1
    - sha256
    - sha512
    - adler32
    - crc32
  when:
    event: tag
